knpu_oauth2_client:
    clients:
        oidc:
            type: keycloak
            auth_server_url: http://localhost:8080/auth
            realm: oidc
            client_id: '%env(CLIENT_ID)%'
            client_secret: '%env(CLIENT_SECRET)%'
            redirect_route: check
